apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: opziv03ss-java-quarkus
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/rhtap-qe:3249b82868f167a2879bd7c904b821d20e641dff@sha256:d1dfc9377e2c76bdc7150507123afeeaef34c97fdc02b854336099fe62ba7d4b
        name: container-image  
